Revert "include cstdint"
This reverts commit bff91033b0d6c69cd657cc277157fc85d3e0530c.

As travis builds fail with this, due to old g++ headers:
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/bits/c++0x_warning.h:32:2: error:
      This file requires compiler and library support for the upcoming ISO C++
      standard, C++0x. This support is currently experimental, and must be
      enabled with the -std=c++0x or -std=gnu++0x compiler options.
 ^
1 error generated.